// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Keyboard_Settings = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_TxtKeyboard = NULL;
lv_obj_t * ui_InputBLEs = NULL;
lv_obj_t * ui_BtnConnectBLE = NULL;
lv_obj_t * ui_TxtConnect2 = NULL;
// event funtions

// build funtions

void ui_Keyboard_Settings_screen_init(void)
{
    ui_Keyboard_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Keyboard_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Keyboard_Settings);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 20);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Container3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtKeyboard = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_TxtKeyboard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtKeyboard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtKeyboard, 15);
    lv_obj_set_y(ui_TxtKeyboard, 26);
    lv_label_set_text(ui_TxtKeyboard, "Keyboard:");
    lv_obj_set_style_text_font(ui_TxtKeyboard, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputBLEs = lv_dropdown_create(ui_Container3);
    lv_obj_set_width(ui_InputBLEs, 204);
    lv_obj_set_height(ui_InputBLEs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputBLEs, 97);
    lv_obj_set_y(ui_InputBLEs, 15);
    lv_obj_add_flag(ui_InputBLEs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_InputBLEs, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_InputBLEs), &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_InputBLEs), &lv_font_montserrat_14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_BtnConnectBLE = lv_btn_create(ui_Keyboard_Settings);
    lv_obj_set_width(ui_BtnConnectBLE, 100);
    lv_obj_set_height(ui_BtnConnectBLE, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BtnConnectBLE, -3);
    lv_obj_set_y(ui_BtnConnectBLE, 81);
    lv_obj_set_align(ui_BtnConnectBLE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConnectBLE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnConnectBLE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_BtnConnectBLE, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtConnect2 = lv_label_create(ui_BtnConnectBLE);
    lv_obj_set_width(ui_TxtConnect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtConnect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TxtConnect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtConnect2, "Connect");
    lv_obj_set_style_text_font(ui_TxtConnect2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Keyboard_Settings_screen_destroy(void)
{
    if(ui_Keyboard_Settings) lv_obj_del(ui_Keyboard_Settings);

    // NULL screen variables
    ui_Keyboard_Settings = NULL;
    ui_Container3 = NULL;
    ui_TxtKeyboard = NULL;
    ui_InputBLEs = NULL;
    ui_BtnConnectBLE = NULL;
    ui_TxtConnect2 = NULL;

}
