// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_LoadingBar = NULL;
lv_obj_t * ui_LoadingTxt = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Splash);
    lv_img_set_src(ui_Image1, &ui_img_splash_clean_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -25);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoadingBar = lv_bar_create(ui_Splash);
    lv_obj_set_height(ui_LoadingBar, 10);
    lv_obj_set_width(ui_LoadingBar, lv_pct(100));
    lv_obj_set_align(ui_LoadingBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_LoadingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoadingBar, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LoadingBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoadingBar, lv_color_hex(0xAAAAAA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LoadingTxt = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_LoadingTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadingTxt, 10);
    lv_obj_set_y(ui_LoadingTxt, -15);
    lv_obj_set_align(ui_LoadingTxt, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LoadingTxt, "Connecting to WIFI...");
    lv_obj_set_style_text_font(ui_LoadingTxt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_Image1 = NULL;
    ui_LoadingBar = NULL;
    ui_LoadingTxt = NULL;

}
